apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: xaqwoku2j-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-81a9dcf77e.chs8.p3.openshiftapps.com/rhtap/rhtap-qe-java-springboot:6547c4da3fb95708678be83745a391f5356ca69e@sha256:4c273e43d2682db91ff926acb6210568ec993c3232438a0fc13290e98686d0d9
          name: container-image
